[package]
name = "ender"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["server"]
resolver = "2"

[dependencies]
server = { path = "./server" }

[dev-dependencies]
divan = "0.1.14"

[[bench]]
name = "sandbox"
harness = false

[profile.release]
strip = true
lto = true
codegen-units = 1
