[package]
name = "ender"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = { version = "0.7.4", features = ["serde"] }
derive_more = { version = "1.0.0", features = ["full"] }
fastbuf = "0.20.0"
fastvarint = "0.3.0"
mio = { version = "1.0.1", features = ["os-poll", "net"] }
nonmax = { version = "0.5.5", features = ["serde"] }
packetize = "0.78.0"
rand = "0.8.5"
rsa = "0.9.6"
rsa-der = "0.3.0"
serde = { version = "1.0.206", features = ["derive"] }
simd-json = "0.13.10"
slab = "0.4.9"
tick-machine = "0.5.0"
uuid = { version = "1.10.0", features = ["serde"] }

[dev-dependencies]
divan = "0.1.14"

[[bench]]
name = "sandbox"
harness = false

[profile.release]
strip = true
lto = true
codegen-units = 1
